### ISSUE TITLE
描写範囲外に行くと椅子がピンク色のハテナとして描写される問題

### ISSUE THREAD

**Issue by waya0125** [Kotatsu-RTM/fixRTM#4]
これのせいでいつでも地上子削除の危険性と隣合わせです。

**Comment by Siro256** [comment]
cb1ffd99fc5ffab0d0e520e00e5b10b4c0e965f1 にて車両の存在するチャンクが強制的に読み込まれるよう変更したので発生しないはずです  確認待ち

**Comment by waya0125** [comment]
確認ができました。ありがとうございました。
